
############################
## IRODS server
irods:
  image: irods/icat:4.0.3
  hostname: rodserver
  command: mytest
  ports:
  - 1247/tcp
  links:
  - graphdb:neo
  tty: true

############################
## IRODS clients (+ python?)
icom:
  #image: irods/icommands:4.0.3
  #image: pdonorio/neoicommands
  build: docker_images/iclient
  # labels:
  #   io.rancher.scheduler.global: 'true'
  hostname: iclient
  user: dev
  links:
  - irods:rodserver
  - graphdb:neo
  stdin_open: true
  volumes:
  - ../irodsgraph:/data
  working_dir: /data
  restart: on-failure:1
  tty: true

############################
## neo4j
graphdb:
    image: neo4j/neo4j
    volumes:
      - eudat_graphdata:/data
    hostname: neo
    environment:
        NEO4J_AUTH: neo4j/eudat
    ports:
        - 8000:7474
  # build: docker_images/graphvbox
  # # Based on official beta https://hub.docker.com/r/neo4j/neo4j/
  # volumes:
  # - eudat_graphdata:/data
  # #- ../data/graphserver:/data
  # - ./docker_images/graphvbox/neo4j_server.conf:/conf/neo4j-server.properties
  # # labels:
  # #   io.rancher.scheduler.affinity:host_label_ne: anet=pub
  # #   io.rancher.scheduler.affinity:host_label: anet=pub
  # hostname: neo
  # expose:
  #     - 7474
  # ports:
  #     - 7777:7474/tcp
  # restart: 'no'
  # environment:
  #   NEO4J_AUTH: none # No passw otherwise the web server is not accessible
  # tty: true
  # stdin_open: true
  # cap_add:
  # - SYS_RESOURCE

############################
## Jupyter project - ipython notebook
notebook:
  image: pdonorio/jupy3dataslide
  hostname: nb
  ports:
  - 8080:8888/tcp
  volumes:
  - ../notebooks:/data:rw
  #- ../irodsgraph/libs/:/data/libs:ro
  - ../irodsgraph/libs/:/root/.ipython/libs:ro
  - ./jupy.conf:/root/.jupyter/jupyter_notebook_config.py
  links:
  - graphdb:neo
